/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import facebookbd.MemoriaLocal;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.bean.ComentarioPost;
import model.bean.Post;
import model.bean.Usuario;
import model.dao.ComentarioPostDAO;
import model.dao.PostDAO;

/**
 *
 * @author icaro
 */
public class TelaDoPost extends javax.swing.JFrame {
    Post post;
    Map<Integer, ComentarioPost> mapaDeComentarios = new HashMap<>();
    
    public TelaDoPost(Post post) {
        this.post = post;
        initComponents();
        this.configurarComponentesDaTela();
    }
    
    DefaultListModel modeloDaListaDeComentarios;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltarButton = new javax.swing.JButton();
        facebookLabel = new javax.swing.JLabel();
        postLabel = new javax.swing.JLabel();
        conteudoPostLabel = new javax.swing.JLabel();
        espacoComentarTextfield = new javax.swing.JTextField();
        comentarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentariosList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 98, 158));

        voltarButton.setBackground(new java.awt.Color(255, 255, 255));
        voltarButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(70, 98, 158));
        voltarButton.setText("VOLTAR");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        facebookLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        facebookLabel.setForeground(new java.awt.Color(255, 255, 255));
        facebookLabel.setText("FACEBOOK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(facebookLabel)
                .addGap(235, 235, 235)
                .addComponent(voltarButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(facebookLabel)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        postLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        postLabel.setText("POST");

        conteudoPostLabel.setBackground(new java.awt.Color(255, 255, 255));
        conteudoPostLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conteudoPostLabel.setText("conteudo post");

        comentarButton.setBackground(new java.awt.Color(255, 255, 255));
        comentarButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        comentarButton.setForeground(new java.awt.Color(70, 98, 158));
        comentarButton.setText("COMENTAR");
        comentarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comentarButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(comentariosList);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("COMENTÁRIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(postLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(espacoComentarTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comentarButton))
                    .addComponent(conteudoPostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(postLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conteudoPostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(espacoComentarTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comentarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Perfil().setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void comentarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comentarButtonActionPerformed
        // TODO add your handling code here:
        ComentarioPost comentraioNoPost = new ComentarioPost(post.getId_post(), MemoriaLocal.usuarioLogado.getId_usuario(), "www.jpg.com", espacoComentarTextfield.getText());
        ComentarioPostDAO.create(comentraioNoPost);
        this.inserirComentraioNoPost(comentraioNoPost);
        
        espacoComentarTextfield.setText("");
    }//GEN-LAST:event_comentarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoPost(null).setVisible(true);
            }
        });
    }
    
    private void configurarComponentesDaTela() {
        this.conteudoPostLabel.setText(this.post.getConteudo());
        this.configurarListaDeComentarios();
    }
    
    private void configurarListaDeComentarios(){
        modeloDaListaDeComentarios = new DefaultListModel();
        comentariosList.setModel(modeloDaListaDeComentarios);
        
        int comentariosAdicionados = 0;
        for (ComentarioPost comentarioPost : ComentarioPostDAO.read()){
            if (comentarioPost.getId_post() != post.getId_post()){
                continue;
            }
            this.mapaDeComentarios.put(comentariosAdicionados++, comentarioPost);
            this.inserirComentraioNoPost(comentarioPost);
        }
        
        ListSelectionListener listener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    JList source = (JList)event.getSource();
                    int indiceAtualDaLista = source.getSelectedIndex();
                    ComentarioPost comentariosDesteIndice = mapaDeComentarios.get(indiceAtualDaLista);
                    
                    new TelaDoComentario(comentariosDesteIndice).setVisible(true);
                    
                    dispose();
                }
            }
        };

        this.comentariosList.addListSelectionListener(listener);
    }   
    
    
    public void inserirComentraioNoPost(ComentarioPost comentarioPost){
        modeloDaListaDeComentarios.addElement(comentarioPost.getConteudo() + " - Comentário de: " + comentarioPost.getId_user_coment());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comentarButton;
    private javax.swing.JList<String> comentariosList;
    private javax.swing.JLabel conteudoPostLabel;
    private javax.swing.JTextField espacoComentarTextfield;
    private javax.swing.JLabel facebookLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel postLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
